Music.db/Music.db/ViewModels/Song/DeleteSongViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.ViewModels
{
    public class DeleteSongViewModel
    {
        public int SongID { get; set; }
        public string SongTitle { get; set; }
        public string SongArtist { get; set; }
    }
}

Music.db/Music.db/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Music.db.Data;
using Music.db.Models;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    [Authorize(Roles = "admin")]
    public class AlbumController : Controller
    {
        private readonly MusicDbContext _context;

        public AlbumController(MusicDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            AlbumListViewModel viewModel = new AlbumListViewModel();
            viewModel.Albums = await _context.Albums.OrderBy(x => x.AlbumTitle).ToListAsync();
            return View(viewModel);
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAlbumViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(new Album()
                {
                    AlbumTitle = viewModel.AlbumTitle,
                    //AlbumArtist = viewModel.AlbumArtist,
                    AlbumCover = viewModel.AlbumCover,
                    //Songs = viewModel.Songs
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums.FirstOrDefaultAsync(x => x.ID == id);
            if (album == null)
            {
                return NotFound();
            }

            DeleteAlbumViewModel viewModel = new DeleteAlbumViewModel()
            {
                AlbumID = album.ID,
                AlbumTitle = album.AlbumTitle,
                //AlbumArtist = album.AlbumArtist,
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            List<Song> songs = _context.Songs.Include(a => a.Genre)
                                 .Include(x => x.Remixer)
                                 .Where(x => x.AlbumID == id).ToList();

            foreach (var song in songs)
            {
                song.AlbumID = null;
            }

            var album = await _context.Albums.FindAsync(id);
            _context.Albums.Remove(album);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            Album album = _context.Albums.Where(x => x.ID == id).FirstOrDefault();
            List<Song> songs = _context.Songs.Include(a => a.Genre)
                                             .Include(x => x.Remixer)
                                             .Where(x => x.AlbumID == id).ToList();

            ICollection<SongArtist> songArtists = _context.SongArtists.Include(x => x.Song.Album)
                                                                      .Include(x => x.Artist)
                                                                      .Where(x => x.Song.AlbumID == id)
                                                                      .ToList();
            List<string> artists = new List<string>();
            string artistName = "";

            foreach (var artist in songArtists)
            {
                artists.Add(artist.Artist.Name);
            }

            List<string> noduplicates = artists.Distinct().ToList();

            if (noduplicates.Count() != 0)
            {
                if (noduplicates.Count() == 1)
                {
                    artistName = artists[0];
                }
                else
                {
                    artistName = "Various";
                }
            }
            else
            {
                artistName = "No artists...";
            }

            if (album != null)
            {
                AlbumDetailsViewModel viewModel = new AlbumDetailsViewModel()
                {
                    AlbumTitle = album.AlbumTitle,
                    Songs = songs,
                    SongArtists = songArtists,
                    ArtistName = artistName
                };
                return View(viewModel);
            }
            else
            {
                AlbumListViewModel viewModel = new AlbumListViewModel()
                {
                    Albums = _context.Albums.ToList()
                };
                return View("Index", viewModel);
            }
        }

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }

            EditAlbumViewModel viewModel = new EditAlbumViewModel()
            {
                AlbumID = album.ID,
                AlbumTitle = album.AlbumTitle,
                AlbumCover = album.AlbumCover,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditAlbumViewModel viewModel)
        {
            if (id != viewModel.AlbumID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Album album = new Album()
                    {
                        ID = viewModel.AlbumID,
                        AlbumTitle = viewModel.AlbumTitle,
                        AlbumCover = viewModel.AlbumCover,
                    };
                    _context.Update(album);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Albums.Any(x => x.ID == viewModel.AlbumID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        #endregion

        [AllowAnonymous]
        public async Task<IActionResult> Search(AlbumListViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.AlbumSearch))
            {
                viewModel.Albums = await _context.Albums.Where(x => x.AlbumTitle.Contains(viewModel.AlbumSearch)).ToListAsync();
            }
            else
            {
                viewModel.Albums = await _context.Albums.ToListAsync();
            }
            return View("Index", viewModel);
        }

    }
}

Music.db/Music.db/Controllers/SongController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music.db.Data;
using Music.db.Models;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    [Authorize(Roles = "admin")]
    public class SongController : Controller
    {
        private readonly MusicDbContext _context;

        public SongController(MusicDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            SongListViewModel viewModel = new SongListViewModel();
            viewModel.Songs = await _context.Songs.Include(a => a.Album)
                                                  .Include(b => b.Remixer)
                                                  .OrderByDescending(x => x.ReleaseDate)
                                                  .ToListAsync();

            viewModel.SongArtists = await _context.SongArtists.Include(x => x.Artist).ToListAsync();

            return View(viewModel);
        }

        //public IActionResult CreateOffCanvas()
        //{
        //    return View();
        //}

        #region Create
        public async Task<IActionResult> Create()
        {
            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            CreateSongViewModel viewModel = new CreateSongViewModel()
            {
                //SelectListItem with default null value 
                Albums = new SelectList(albums.OrderBy(x => x.AlbumTitle), "ID", "AlbumTitle", 0),
                Genres = new SelectList(await _context.Genres.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 0),
                Artists = new SelectList(await _context.Artists.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 1),
                Remixers = new SelectList(remixers.OrderBy(x => x.Name), "ID", "Name", 0)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSongViewModel viewModel)
        {
            Song songindb = await _context.Songs.Where(x => x.SongTitle == viewModel.SongTitle)
                                       .Where(x => x.AlbumID == viewModel.AlbumID)
                                       .Where(x => x.BPM == viewModel.BPM)
                                       .Where(x => x.EditSongLength == viewModel.EditSongLength)
                                       .Where(x => x.ExtendedSongLength == viewModel.ExtendedSongLength)
                                       .Where(x => x.GenreID == viewModel.GenreID)
                                       .Where(x => x.Key == viewModel.Key)
                                       .Where(x => x.ReleaseDate == viewModel.ReleaseDate)
                                       .Where(x => x.RemixerID == viewModel.RemixerID)
                                       .FirstOrDefaultAsync();

            if (songindb != null)
            {
                ModelState.AddModelError("DuplicateError", "Error, you tried to make a duplicate!");
            }

            if (viewModel.EditSongLength == null && viewModel.ExtendedSongLength == null)
            {
                ModelState.AddModelError("SongLenghtError", "Error, a song has at least one length!");
            }

            if (ModelState.IsValid)
            {
                Song song = new Song()
                {
                    SongTitle = viewModel.SongTitle,
                    AlbumID = (viewModel.AlbumID == 0) ? null : viewModel.AlbumID,
                    GenreID = viewModel.GenreID,
                    RemixerID = (viewModel.RemixerID == 0) ? null : viewModel.RemixerID,
                    BPM = viewModel.BPM,
                    EditSongLength = viewModel.EditSongLength,
                    ExtendedSongLength = viewModel.ExtendedSongLength,
                    Key = viewModel.Key,
                    ReleaseDate = viewModel.ReleaseDate,
                };

                _context.Add(song);
                await _context.SaveChangesAsync();

                foreach (var artist in viewModel.SelectedArtists)
                {
                    SongArtist songArtist = new SongArtist()
                    {
                        SongID = song.ID,
                        ArtistID = artist
                    };
                    _context.Add(songArtist);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            viewModel.Albums = new SelectList(albums.OrderBy(x => x.AlbumTitle), "ID", "AlbumTitle", 0);
            viewModel.Genres = new SelectList(await _context.Genres.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 0);
            viewModel.Artists = new SelectList(await _context.Artists.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 1);
            viewModel.Remixers = new SelectList(remixers.OrderBy(x => x.Name), "ID", "Name", 0);

            return View(viewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FirstOrDefaultAsync(k => k.ID == id);
            if (song == null)
            {
                return NotFound();
            }

            DeleteSongViewModel viewModel = new DeleteSongViewModel()
            {
                SongID = song.ID,
                SongTitle = song.SongTitle,
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ICollection<SongArtist> songArtists = await _context.SongArtists.Where(x => x.SongID == id).ToListAsync();

            foreach (var songArtist in songArtists)
            {
                _context.SongArtists.Remove(songArtist);
            }
            var song = await _context.Songs.FindAsync(id);
            _context.Songs.Remove(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Song song = _context.Songs.Include(x => x.Album)
                                      .Include(x => x.Genre)
                                      .Include(x => x.Remixer)
                                      .Include(x => x.SongArtists)
                                      .Where(x => x.ID == id)
                                      .FirstOrDefault();

            ICollection<SongArtist> songArtists = _context.SongArtists.Include(x => x.Artist)
                                                                      .Where(x => x.SongID == song.ID).ToList();

            if (song != null)
            {
                SongDetailsViewModel viewModel = new SongDetailsViewModel()
                {
                    SongTitle = song.SongTitle,
                    SongArtists = songArtists,
                    Album = song.Album,
                    Genre = song.Genre,
                    Remixer = song.Remixer,
                    BPM = song.BPM,
                    EditSongLength = song.EditSongLength,
                    ExtendedSongLength = song.ExtendedSongLength,
                    Key = song.Key,
                    ReleaseDate = song.ReleaseDate,
                };
                return View(viewModel);
            }
            else
            {
                SongListViewModel viewModel = new SongListViewModel()
                {
                    Songs = _context.Songs.ToList()
                };
                return View("Index", viewModel);
            }
        }

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            ICollection<SongArtist> songArtists = await _context.SongArtists.Include(x => x.Artist)
                                                          .Where(x => x.SongID == song.ID).ToListAsync();

            string artistNames = "";
            foreach (var artist in songArtists)
            {
                artistNames += $"{artist.Artist.Name}, ";
            }

            EditSongViewModel viewModel = new EditSongViewModel()
            {
                SongID = song.ID,
                SongTitle = song.SongTitle,
                ArtistNames = artistNames,
                AlbumID = song.AlbumID,
                GenreID = song.GenreID,
                RemixerID = song.RemixerID,

Music.db/Music.db/Views/Song/Create.cshtml
@model Music.db.ViewModels.CreateSongViewModel

@{
    ViewData["Title"] = "Create Song";
}

<div class="row pt-5">
    <h2>New Song</h2>

    <hr>
    <div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <span asp-validation-for="DuplicateError" class="text-danger"></span>
            <div class="row pb-1">
                <div class="col-md-6">
                    <div class="input-group mb-2">
                        <span class="input-group-text"><label asp-for="SongTitle" class="control-label "></label></span>
                        <input asp-for="SongTitle" class="form-control">
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="SongTitle" class="text-danger"></span>
                    </div>

                    <div class="input-group mb-2">
                        <span class="input-group-text"><label asp-for="ArtistID" class="control-label "></label></span>
                        <select asp-for="SelectedArtists" asp-items="Model.Artists" class="form-control" multiple></select>
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="ArtistID" class="text-danger"></span>
                    </div>

                    <div class="input-group mb-2">
                        <span class="input-group-text"><label asp-for="RemixerID" class="control-label "></label></span>
                        <select asp-for="RemixerID" asp-items="Model.Remixers" class="form-control"></select>
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="RemixerID " class="text-danger"></span>
                    </div>

                    <div class="input-group mb-2">
                        <span class="input-group-text">
                            <label asp-for="AlbumID" class="control-label"></label>
                        </span>
                        <select asp-for="AlbumID" asp-items="Model.Albums" class="form-control"></select>
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="AlbumID " class="text-danger"></span>
                    </div>
                    <div class="input-group mb-2">
                        <span class="input-group-text"><label asp-for="ReleaseDate" class="control-label "></label></span>
                        <input asp-for="ReleaseDate" class="form-control">
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="ReleaseDate " class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row pb-1">
                        <div class="input-group mb-2">
                            <span class="input-group-text">
                                <label asp-for="GenreID" class="control-label"></label>
                            </span>
                            <select asp-for="GenreID" asp-items="Model.Genres" class="form-control"></select>
                        </div>
                        <div class="pb-2">
                            <span asp-validation-for="GenreID" class="text-danger"></span>
                        </div>

                        <div class="input-group mb-2">
                            <span class="input-group-text"><label asp-for="BPM" class="control-label "></label></span>
                            <input asp-for="BPM" min=0 type="number" class="form-control">
                        </div>
                        <div class="pb-2">
                            <span asp-validation-for="BPM " class="text-danger"></span>
                        </div>

                        <div class="input-group mb-2">
                            <span class="input-group-text"><label asp-for="Key" class="control-label "></label></span>
                            <input asp-for="Key" class="form-control">
                        </div>
                        <div class="pb-2">
                            <span asp-validation-for="Key " class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row pb-1">
                        <h6 class="text-center pb-1">Length</h6>
                        <div class="col-md-6">
                            <div class="input-group mb-2">
                                <span class="input-group-text"><label asp-for="EditSongLength" class="control-label "></label></span>
                                <input id="editsonglength" asp-for="EditSongLength" class="form-control">
                            </div>
                            <div class="pb-2">
                                <span asp-validation-for="EditSongLength " class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="input-group mb-2">
                                <span class="input-group-text"><label asp-for="ExtendedSongLength" class="control-label "></label></span>
                                <input asp-for="ExtendedSongLength" class="form-control">
                            </div>
                            <div class="pb-2">
                                <span asp-validation-for="ExtendedSongLength " class="text-danger"></span>
                            </div>
                        </div>
                        <span asp-validation-for="SongLenghtError" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row py-1">
                <div class="col-md-6">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-controller="Song" asp-action="Index" value="" class="btn btn-danger m-1">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music.db/Music.db/Views/Song/Delete.cshtml
@model Music.db.ViewModels.DeleteSongViewModel

@{
    ViewData["Title"] = "Delete Song";
}

<div class="row pt-5">
    <h2>Delete Song</h2>

    <hr />

    <h4>Are you sure you want to delete @Model.SongTitle @*-  @Model.SongArtist*@?</h4>

    <form asp-action="Delete">
        <input type="hidden" asp-for="SongID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Music.db/Music.db/Views/Song/Index.cshtml
@model Music.db.ViewModels.SongListViewModel

@{
    ViewData["Title"] = "Songs";
}

<div class="row pt-5">
    <h2 class="text-center">Songs</h2>
    <div class="row">
        <div class="col">
            <form asp-controller="Song" asp-action="Search" method="get">
                <div class="form-actions no-color">
                    <p>
                        Search song:
                        <input asp-for="SongSearch">
                        <input type="submit" value="Search" class="btn btn-default" />
                        <a asp-controller="Song" asp-action="Index">Back to list</a>
                    </p>
                </div>
            </form>
        </div>
        @if (User.IsInRole("admin"))
        {
            <div class="col text-end">
                <a class="btn btn-primary" asp-controller="Song" asp-action="Create">Create New Song</a>
            </div>
        }
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                @*<th scope="col">
                        Cover
                    </th>*@
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].SongTitle)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].SongArtists)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].Album)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].Remixer)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].EditSongLength)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].ExtendedSongLength)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Songs[0].ReleaseDate)
                </th>
                <th scope="col">
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var song in Model.Songs)
            {
                <tr>
                    @*<td class="col">
                            <a asp-controller="Song"
                               asp-action="Details"
                               asp-route-id="@song.ID">
                                Mini Cover hier
                                <img src="@Url.Content("~/img/" + (song.SongArtist.Replace(", ", " ").Replace(" ", "_") + "-" + song.SongTitle.Replace(" ","_")).Replace(",","_").ToLower() + ".jpg")" style="width:50px;">
                            </a>
                        </td>*@
                    <td class="col">
                        <a asp-controller="Song"
                           asp-action="Details"
                           asp-route-id="@song.ID">
                            @song.SongTitle
                        </a>
                        @if (song.Remixer != null)
                        {<span>
                                <a asp-controller="Song"
                                   asp-action="Details"
                                   asp-route-id="@song.ID">
                                    (@song.Remixer.Name Remix)
                                </a>
                            </span>
                        }
                    </td>
                    <td class="col">
                        @if (Model.SongArtists != null)
                        {
                            foreach (var songArtist in Model.SongArtists.Where(x => x.SongID == song.ID))
                            {
                                <a asp-controller="Artist"
                                   asp-action="Details"
                                   asp-route-id="@songArtist.ArtistID">
                                    @songArtist.Artist.Name,
                                </a>
                            }
                        }
                        else
                        {
                            <span>error</span>
                        }
                    </td>

                    <td class="col">
                        @if (song.AlbumID != null)
                        {
                            <a asp-controller="Album"
                               asp-action="Details"
                               asp-route-id="@song.AlbumID">
                                @song.Album.AlbumTitle
                            </a>
                        }
                        else
                        {
                            @song.SongTitle
                        }
                    </td>
                    <td class="col">
                        @if (song.Remixer != null)
                        {
                            <a asp-controller="Artist"
                               asp-action="Details"
                               asp-route-id="@song.RemixerID">
                                @song.Remixer.Name
                            </a>
                        }
                    </td>
                    <td class="col">
                        @song.EditSongLength
                    </td>
                    <td class="col">
                        @song.ExtendedSongLength
                    </td>
                    <td class="col">
                        @song.ReleaseDate.ToString("yyyy")
                    </td>
                    <td class="col">
                        @*<div class="d-flex gap-2">
                            <form asp-action="AddToCollection">
                                <input type="hidden" asp-for="@song.ID" />
                                <button type="submit" class="btn btn-default">
                                    <i class="bi bi-heart-fill"></i>
                                </button>
                            </form>
                            <form asp-action="RemoveFromCollection">
                                <input type="hidden" asp-for="@song.ID" />
                                <button type="submit" class="btn btn-default">
                                    <i class="bi bi-heart"></i>
                                </button>
                            </form>
                        </div>*@
                        @if (User.IsInRole("admin"))
                        {<span>
                                <a asp-controller="Song"
                                   asp-action="Edit"
                                   asp-route-id="@song.ID">Edit</a> |
                                <a asp-controller="Song"
                                   asp-action="Delete"
                                   asp-route-id="@song.ID">Delete</a>
                            </span>
                        }


                    </td>
                    <th class="col">
                        &nbsp;
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>