Music.db/Music.db/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Models
{
    public class Genre
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public List<Song> Songs { get; set; }
    }
}

Music.db/Music.db/ViewModels/Genre/CreateGenreViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.ViewModels
{
    public class CreateGenreViewModel
    {
        [Required]
        public string Name { get; set; }

        public string DuplicateError { get; set; }
    }
}

Music.db/Music.db/ViewModels/Genre/DeleteGenreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.ViewModels
{
    public class DeleteGenreViewModel
    {
        public int GenreID { get; set; }
        public string Name { get; set; }

        public string Error { get; set; }
    }
}

Music.db/Music.db/ViewModels/Genre/EditGenreViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.ViewModels
{
    public class EditGenreViewModel
    {
        public int GenreID { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

Music.db/Music.db/ViewModels/Genre/GenreListViewModel.cs
using Music.db.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.ViewModels
{
    public class GenreListViewModel
    {
        public List<Genre> Genres { get; set; }
        public string GenreSearch { get; set; }
    }
}

Music.db/Music.db/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Music.db.Data;
using Music.db.Models;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    [Authorize(Roles = "admin")]
    public class GenreController : Controller
    {
        private readonly MusicDbContext _context;

        public GenreController(MusicDbContext context)
        {
            _context = context;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            GenreListViewModel viewModel = new GenreListViewModel();
            viewModel.Genres = await _context.Genres.OrderBy(x => x.Name).ToListAsync();
            return View(viewModel);
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGenreViewModel viewModel)
        {
            var genreindb = await _context.Genres.Where(x => x.Name == viewModel.Name).FirstOrDefaultAsync();

            if (genreindb != null)
            {
                ModelState.AddModelError("DuplicateError", "Error, you tried to make a duplicate!");
            }

            if (ModelState.IsValid)
            {
                _context.Add(new Genre()
                {
                    Name = viewModel.Name,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FirstOrDefaultAsync(x => x.ID == id);
            if (genre == null)
            {
                return NotFound();
            }

            DeleteGenreViewModel viewModel = new DeleteGenreViewModel()
            {
                GenreID = genre.ID,
                Name = genre.Name,
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = await _context.Genres.FindAsync(id);

            ICollection<SongArtist> songArtists = await _context.SongArtists.Include(x => x.Song)
                                                      .Include(x => x.Song.Genre)
                                                      .Where(x => x.Song.GenreID == id)
                                                      .ToListAsync();
            if (songArtists.Count() == 0)
            {
                _context.Genres.Remove(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("Error", "First delete all the songs with this genre before deleting this genre!");
                DeleteGenreViewModel viewModel = new DeleteGenreViewModel()
                {
                    GenreID = genre.ID,
                    Name = genre.Name,
                };

                return View(viewModel);
            }
        }
        #endregion

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }

            EditGenreViewModel viewModel = new EditGenreViewModel()
            {
                GenreID = genre.ID,
                Name = genre.Name,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditGenreViewModel viewModel)
        {
            if (id != viewModel.GenreID)
            {
                return NotFound();
            }

            var genreindb = await _context.Genres.Where(x => x.Name == viewModel.Name).FirstOrDefaultAsync();

            if (genreindb != null)
            {
                ModelState.AddModelError("DuplicateError", "Error, you tried to make a duplicate!");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Genre genre = new Genre()
                    {
                        ID = viewModel.GenreID,
                        Name = viewModel.Name,
                    };
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Genres.Any(x => x.ID == viewModel.GenreID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        #endregion

        [AllowAnonymous]
        public async Task<IActionResult> Search(GenreListViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.GenreSearch))
            {
                viewModel.Genres = await _context.Genres.Where(x => x.Name.Contains(viewModel.GenreSearch)).ToListAsync();
            }
            else
            {
                viewModel.Genres = await _context.Genres.ToListAsync();
            }
            return View("Index", viewModel);
        }

    }
}

Music.db/Music.db/Views/Genre/Create.cshtml
@model Music.db.ViewModels.CreateGenreViewModel

@{
    ViewData["Title"] = "Create Genre";
}

<div class="row pt-5">
    <h2>New Genre</h2>

    <hr>
    <div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <span asp-validation-for="DuplicateError" class="text-danger"></span>
            <div class="row pb-1">
                <div class="col-md-6">
                    <div class="input-group mb-2">
                        <span class="input-group-text"><label asp-for="Name" class="control-label "></label></span>
                        <input asp-for="Name" class="form-control">
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="Name " class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row py-1">
                <div class="col-md-6">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-controller="Genre" asp-action="Index" value="" class="btn btn-danger m-1">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music.db/Music.db/Views/Genre/Delete.cshtml
@model Music.db.ViewModels.DeleteGenreViewModel

@{
    ViewData["Title"] = "Delete Genre";
}

<div class="row pt-5">
    <h2>Delete Genre</h2>

    <hr />

    <h4>Are you sure you want to delete @Model.Name?</h4>

    <form asp-action="Delete">
        <input type="hidden" asp-for="GenreID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <div class="row py-3">
            <span asp-validation-for="Error" class="text-danger"></span>
        </div>
    </form>
</div>

Music.db/Music.db/Views/Genre/Edit.cshtml
@model Music.db.ViewModels.EditGenreViewModel

@{
    ViewData["Title"] = "Edit Genre";
}

<div class="row pt-5">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="GenreID" />
        <div class="row pb-1">
            <div class="col-md-6">
                @*<label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>*@
                <div class="input-group mb-2">
                    <span class="input-group-text"><label asp-for="Name" class="control-label "></label></span>
                    <input asp-for="Name" class="form-control">
                </div>
                <div class="pb-2">
                    <span asp-validation-for="Name " class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <input type="submit" value="Edit" class="btn btn-primary" />
                <a asp-controller="Genre" asp-action="Index" value="" class="btn btn-danger m-1">Cancel</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music.db/Music.db/Views/Genre/Index.cshtml
@model Music.db.ViewModels.GenreListViewModel

@{
    ViewData["Title"] = "Genres";
}

<div class="row pt-5">
    <h2 class="text-center">Genres</h2>

    <div class="row">
        <div class="col">
            <form asp-controller="Genre" asp-action="Search" method="get">
                <div class="form-actions no-color">
                    <p>
                        Search genre:
                        <input asp-for="GenreSearch">
                        <input type="submit" value="Search" class="btn btn-default" />
                        <a asp-controller="Genre" asp-action="Index">Back to list</a>
                    </p>
                </div>
            </form>
        </div>
        @if (User.IsInRole("admin"))
        {
            <div class="col text-end">
                <a class="btn btn-primary" asp-controller="Genre" asp-action="Create">Create New Genre</a>
            </div>}
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(s => s.Genres[0].Name)
                </th>
                @*<th scope="col">
                        Subgenres
                    </th>*@
                <th scope="col">
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var genre in Model.Genres)
            {
                <tr>
                    <td class="col">
                        @genre.Name
                    </td>
                    @*<td class="col">
                            subgenres hier
                        </td>*@
                    <td class="col">
                        @if (User.IsInRole("admin"))
                        {<span>
                                <a asp-controller="Genre"
                                   asp-action="Edit"
                                   asp-route-id="@genre.ID">Edit</a> |
                                <a asp-controller="Genre"
                                   asp-action="Delete"
                                   asp-route-id="@genre.ID">Delete</a>
                            </span>
                        }
                    <td class="col">
                        &nbsp;
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>