Music.db/Music.db/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Music.db.Data;
using Music.db.Models;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    [Authorize(Roles = "admin")]
    public class ArtistController : Controller
    {
        private readonly MusicDbContext _context;

        public ArtistController(MusicDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            ArtistListViewModel viewModel = new ArtistListViewModel();
            viewModel.Artists = await _context.Artists.OrderBy(x => x.Name).ToListAsync();
            return View(viewModel);
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateArtistViewModel viewModel)
        {
            var artistindb = await _context.Artists.Where(x => x.Name == viewModel.Name).FirstOrDefaultAsync();

            if (artistindb != null)
            {
                ModelState.AddModelError("DuplicateError", "Error, you tried to make a duplicate!");
            }

            if (ModelState.IsValid)
            {
                _context.Add(new Artist()
                {
                    Name = viewModel.Name,
                    //Members = viewModel.Members,
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FirstOrDefaultAsync(x => x.ID == id);
            if (artist == null)
            {
                return NotFound();
            }

            DeleteArtistViewModel viewModel = new DeleteArtistViewModel()
            {
                ArtistID = artist.ID,
                Name = artist.Name,
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.FindAsync(id);
            ICollection<SongArtist> songArtists = await _context.SongArtists.Include(x => x.Song)
                                                                  .Include(x => x.Song.Album)
                                                                  .Include(x => x.Artist)
                                                                  .Where(x => x.ArtistID == id)
                                                                  .ToListAsync();
            if (songArtists.Count() == 0)
            {

                _context.Artists.Remove(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("Error", "First delete all the songs of this artist before deleting the artist!");
                DeleteArtistViewModel viewModel = new DeleteArtistViewModel()
                {
                    ArtistID = artist.ID,
                    Name = artist.Name,
                };

                return View(viewModel);
            }

        }
        #endregion

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            Artist artist = await _context.Artists.Where(x => x.ID == id).FirstOrDefaultAsync();

            ICollection<SongArtist> songsOfArtist = await _context.SongArtists.Include(x => x.Song)
                                                                              .Include(x => x.Song.Album)
                                                                              .Include(x => x.Artist)
                                                                              .Where(x => x.ArtistID == id)
                                                                              .ToListAsync();

            ICollection<SongArtist> songArtists = await _context.SongArtists.Include(x => x.Artist)
                                                                            .ToListAsync();

            if (artist != null)
            {
                ArtistDetailsViewModel viewModel = new ArtistDetailsViewModel()
                {
                    Name = artist.Name,
                    //Members = artist.Members,
                    SongsOfArtist = songsOfArtist,
                    SongArtists = songArtists,
                };
                return View(viewModel);
            }
            else
            {
                ArtistListViewModel viewModel = new ArtistListViewModel()
                {
                    Artists = _context.Artists.ToList()
                };
                return View("Index", viewModel);
            }
        }

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }

            EditArtistViewModel viewModel = new EditArtistViewModel()
            {
                ArtistID = artist.ID,
                Name = artist.Name,
                //Members = artist.Members,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditArtistViewModel viewModel)
        {
            if (id != viewModel.ArtistID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Artist artist = new Artist()
                    {
                        ID = viewModel.ArtistID,
                        Name = viewModel.Name,
                        //Members = viewModel.Members,
                    };
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Artists.Any(x => x.ID == viewModel.ArtistID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        #endregion

        [AllowAnonymous]
        public async Task<IActionResult> Search(ArtistListViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.ArtistSearch))
            {
                viewModel.Artists = await _context.Artists.Where(x => x.Name.Contains(viewModel.ArtistSearch)/* ||
                                                    x.Members.Contains(viewModel.ArtistSearch)*/).ToListAsync();
            }
            else
            {
                viewModel.Artists = await _context.Artists.ToListAsync();
            }
            return View("Index", viewModel);
        }

    }
}

Music.db/Music.db/Controllers/SongController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music.db.Data;
using Music.db.Models;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    [Authorize(Roles = "admin")]
    public class SongController : Controller
    {
        private readonly MusicDbContext _context;

        public SongController(MusicDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            SongListViewModel viewModel = new SongListViewModel();
            viewModel.Songs = await _context.Songs.Include(a => a.Album)
                                                  .Include(b => b.Remixer)
                                                  .OrderByDescending(x => x.ReleaseDate)
                                                  .ToListAsync();

            viewModel.SongArtists = await _context.SongArtists.Include(x => x.Artist).ToListAsync();

            return View(viewModel);
        }

        //public IActionResult CreateOffCanvas()
        //{
        //    return View();
        //}

        #region Create
        public async Task<IActionResult> Create()
        {
            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            CreateSongViewModel viewModel = new CreateSongViewModel()
            {
                //SelectListItem with default null value 
                Albums = new SelectList(albums.OrderBy(x => x.AlbumTitle), "ID", "AlbumTitle", 0),
                Genres = new SelectList(await _context.Genres.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 0),
                Artists = new SelectList(await _context.Artists.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 1),
                Remixers = new SelectList(remixers.OrderBy(x => x.Name), "ID", "Name", 0)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSongViewModel viewModel)
        {
            Song songindb = await _context.Songs.Where(x => x.SongTitle == viewModel.SongTitle)
                                       .Where(x => x.AlbumID == viewModel.AlbumID)
                                       .Where(x => x.BPM == viewModel.BPM)
                                       .Where(x => x.EditSongLength == viewModel.EditSongLength)
                                       .Where(x => x.ExtendedSongLength == viewModel.ExtendedSongLength)
                                       .Where(x => x.GenreID == viewModel.GenreID)
                                       .Where(x => x.Key == viewModel.Key)
                                       .Where(x => x.ReleaseDate == viewModel.ReleaseDate)
                                       .Where(x => x.RemixerID == viewModel.RemixerID)
                                       .FirstOrDefaultAsync();

            if (songindb != null)
            {
                ModelState.AddModelError("DuplicateError", "Error, you tried to make a duplicate!");
            }

            if (viewModel.EditSongLength == null && viewModel.ExtendedSongLength == null)
            {
                ModelState.AddModelError("SongLenghtError", "Error, a song has at least one length!");
            }

            if (ModelState.IsValid)
            {
                Song song = new Song()
                {
                    SongTitle = viewModel.SongTitle,
                    AlbumID = (viewModel.AlbumID == 0) ? null : viewModel.AlbumID,
                    GenreID = viewModel.GenreID,
                    RemixerID = (viewModel.RemixerID == 0) ? null : viewModel.RemixerID,
                    BPM = viewModel.BPM,
                    EditSongLength = viewModel.EditSongLength,
                    ExtendedSongLength = viewModel.ExtendedSongLength,
                    Key = viewModel.Key,
                    ReleaseDate = viewModel.ReleaseDate,
                };

                _context.Add(song);
                await _context.SaveChangesAsync();

                foreach (var artist in viewModel.SelectedArtists)
                {
                    SongArtist songArtist = new SongArtist()
                    {
                        SongID = song.ID,
                        ArtistID = artist
                    };
                    _context.Add(songArtist);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            viewModel.Albums = new SelectList(albums.OrderBy(x => x.AlbumTitle), "ID", "AlbumTitle", 0);
            viewModel.Genres = new SelectList(await _context.Genres.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 0);
            viewModel.Artists = new SelectList(await _context.Artists.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 1);
            viewModel.Remixers = new SelectList(remixers.OrderBy(x => x.Name), "ID", "Name", 0);

            return View(viewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FirstOrDefaultAsync(k => k.ID == id);
            if (song == null)
            {
                return NotFound();
            }

            DeleteSongViewModel viewModel = new DeleteSongViewModel()
            {
                SongID = song.ID,
                SongTitle = song.SongTitle,
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ICollection<SongArtist> songArtists = await _context.SongArtists.Where(x => x.SongID == id).ToListAsync();

            foreach (var songArtist in songArtists)
            {
                _context.SongArtists.Remove(songArtist);
            }
            var song = await _context.Songs.FindAsync(id);
            _context.Songs.Remove(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Song song = _context.Songs.Include(x => x.Album)
                                      .Include(x => x.Genre)
                                      .Include(x => x.Remixer)
                                      .Include(x => x.SongArtists)
                                      .Where(x => x.ID == id)
                                      .FirstOrDefault();

            ICollection<SongArtist> songArtists = _context.SongArtists.Include(x => x.Artist)
                                                                      .Where(x => x.SongID == song.ID).ToList();

            if (song != null)
            {
                SongDetailsViewModel viewModel = new SongDetailsViewModel()
                {
                    SongTitle = song.SongTitle,
                    SongArtists = songArtists,
                    Album = song.Album,
                    Genre = song.Genre,
                    Remixer = song.Remixer,
                    BPM = song.BPM,
                    EditSongLength = song.EditSongLength,
                    ExtendedSongLength = song.ExtendedSongLength,
                    Key = song.Key,
                    ReleaseDate = song.ReleaseDate,
                };
                return View(viewModel);
            }
            else
            {
                SongListViewModel viewModel = new SongListViewModel()
                {
                    Songs = _context.Songs.ToList()
                };
                return View("Index", viewModel);
            }
        }

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            ICollection<SongArtist> songArtists = await _context.SongArtists.Include(x => x.Artist)
                                                          .Where(x => x.SongID == song.ID).ToListAsync();

            string artistNames = "";
            foreach (var artist in songArtists)
            {
                artistNames += $"{artist.Artist.Name}, ";
            }

            EditSongViewModel viewModel = new EditSongViewModel()
            {
                SongID = song.ID,
                SongTitle = song.SongTitle,
                ArtistNames = artistNames,
                AlbumID = song.AlbumID,
                GenreID = song.GenreID,
                RemixerID = song.RemixerID,

Music.db/Music.db/Views/Artist/Create.cshtml
@model Music.db.ViewModels.CreateArtistViewModel

@{
    ViewData["Title"] = "Create Artist";
}

<div class="row pt-5">
    <h2>New Artist</h2>

    <hr>
    <div class="row">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <span asp-validation-for="DuplicateError" class="text-danger"></span>
            <div class="row pb-1">
                <div class="col-md-6">
                    <div class="input-group mb-2">
                        <span class="input-group-text"><label asp-for="Name" class="control-label "></label></span>
                        <input asp-for="Name" class="form-control">
                    </div>
                    <div class="pb-2">
                        <span asp-validation-for="Name " class="text-danger"></span>
                    </div>
                </div>
                @*<div class="col-md-6">
                <div class="input-group mb-2">
                    <span class="input-group-text"><label asp-for="Members" class="control-label "></label></span>
                    <input asp-for="Members" class="form-control">
                </div>
                <div class="pb-2">
                    <span asp-validation-for="Members " class="text-danger"></span>
                </div>
            </div>*@
            </div>

            <div class="row py-1">
                <div class="col-md-6">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-controller="Artist" asp-action="Index" value="" class="btn btn-danger m-1">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music.db/Music.db/Views/Artist/Delete.cshtml
@model Music.db.ViewModels.DeleteArtistViewModel

@{
    ViewData["Title"] = "Delete Artist";
}

<div class="row pt-5">
    <h2>Delete Artist</h2>

    <hr />

    <h4>Are you sure you want to delete @Model.Name?</h4>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ArtistID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <div class="row py-3">
            <span asp-validation-for="Error" class="text-danger"></span>
        </div>
    </form>
</div>

Music.db/Music.db/Views/Artist/Details.cshtml
@model ArtistDetailsViewModel

@{
    ViewData["Title"] = "Artist Details";
}

<div class="row pt-5">
    <h3>@Model.Name</h3>
    @*@if (Model.Name != Model.Members)
    {
        <h4>@Model.Members</h4>
    }*@
    <h5>Discography</h5>
    <div class="row">
        <div class="col">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        @*<th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].SongCover)
                        </th>*@
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].SongTitle)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].SongArtists)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].Album)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].Remixer)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].EditSongLength)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].ExtendedSongLength)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(s => s.Songs[0].ReleaseDate)
                        </th>
                        <th scope="col">
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var songOfArtist in Model.SongsOfArtist)
                    {
                        <tr>
                            @*<td class="col">
                                <a asp-controller="Song"
                                   asp-action="Details"
                                   asp-route-id="@songOfArtist.SongID">
                                    Mini Cover hier
                                    <img src="@Url.Content("~/img/" + (song.SongArtist.Replace(", ", " ").Replace(" ", "_") + "-" + song.SongTitle.Replace(" ","_")).Replace(",","_").ToLower() + ".jpg")" style="width:50px;">
                                </a>
                            </td>*@
                            <td class="col">
                                <a asp-controller="Song"
                                   asp-action="Details"
                                   asp-route-id="@songOfArtist.SongID">
                                    @songOfArtist.Song.SongTitle
                                </a>
                                @if (songOfArtist.Song.Remixer != null)
                                {<span>
                                        <a asp-controller="Song"
                                           asp-action="Details"
                                           asp-route-id="@songOfArtist.SongID">
                                            (@songOfArtist.Song.Remixer.Name Remix)
                                        </a>
                                    </span>
                                }
                            </td>
                            <td class="col">
                                @if (Model.SongArtists != null)
                                {
                                    foreach (var songArtist in Model.SongArtists.Where(x => x.SongID == songOfArtist.SongID))
                                    {
                                        <a asp-controller="Artist"
                                           asp-action="Details"
                                           asp-route-id="@songArtist.ArtistID">
                                            @songArtist.Artist.Name,
                                        </a>
                                    }
                                }
                                else
                                {
                                    <span>error</span>
                                }
                            </td>

                            <td class="col">
                                @if (songOfArtist.Song.AlbumID != null)
                                {
                                    <a asp-controller="Album"
                                       asp-action="Details"
                                       asp-route-id="@songOfArtist.Song.AlbumID">
                                        @songOfArtist.Song.Album.AlbumTitle
                                    </a>
                                }
                                else
                                {
                                    @songOfArtist.Song.SongTitle
                                }
                            </td>
                            <td class="col">
                                @if (songOfArtist.Song.Remixer != null)
                                {
                                    <a asp-controller="Artist"
                                       asp-action="Details"
                                       asp-route-id="@songOfArtist.Song.RemixerID">
                                        @songOfArtist.Song.Remixer.Name
                                    </a>
                                }
                            </td>
                            <td class="col">
                                @songOfArtist.Song.EditSongLength
                            </td>
                            <td class="col">
                                @songOfArtist.Song.ExtendedSongLength
                            </td>
                            <td class="col">
                                @songOfArtist.Song.ReleaseDate.ToString("yyyy")
                            </td>
                            <td class="col">
                                @*<a class="text-danger" asp-controller="Song"
                                   asp-action="AddToCollection"
                                   asp-route-id="@songOfArtist.SongID">
                                    <i class="bi bi-heart-fill"></i> <i class="bi bi-heart"></i>
                                </a>*@
                                @if (User.IsInRole("admin"))
                                {<span>
                                        <a asp-controller="Song"
                                           asp-action="Edit"
                                           asp-route-id="@songOfArtist.SongID">Edit</a> |
                                        <a asp-controller="Song"
                                           asp-action="Delete"
                                           asp-route-id="@songOfArtist.SongID">Delete</a>
                                    </span>
                                }


                            </td>
                            <th class="col">
                                &nbsp;
                            </th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Music.db/Music.db/Views/Artist/Edit.cshtml
@model Music.db.ViewModels.EditArtistViewModel

@{
    ViewData["Title"] = "Edit Artist";
}

<div class="row pt-5">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ArtistID" />
        <div class="row pb-1">
            <div class="col-md-6">
                <div class="input-group mb-2">
                    <span class="input-group-text"><label asp-for="Name" class="control-label "></label></span>
                    <input asp-for="Name" class="form-control">
                </div>
                <div class="pb-2">
                    <span asp-validation-for="Name " class="text-danger"></span>
                </div>
            </div>
            @*<div class="col-md-6">
                <div class="input-group mb-2">
                    <span class="input-group-text"><label asp-for="Members" class="control-label "></label></span>
                    <input asp-for="Members" class="form-control">
                </div>
                <div class="pb-2">
                    <span asp-validation-for="Members " class="text-danger"></span>
                </div>
            </div>*@
        </div>

        <div class="row py-1">
            <div class="col-md-6">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-controller="Artist" asp-action="Index" value="" class="btn btn-danger m-1">Cancel</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music.db/Music.db/Views/Artist/Index.cshtml
@model Music.db.ViewModels.ArtistListViewModel

@{
    ViewData["Title"] = "Artists";
}

<div class="row pt-5">
    <h2 class="text-center">Artists</h2>

    <div class="row">
        <div class="col">
            <form asp-controller="Artist" asp-action="Search" method="get">
                <div class="form-actions no-color">
                    <p>
                        Search artist:
                        <input asp-for="ArtistSearch">
                        <input type="submit" value="Search" class="btn btn-default" />
                        <a asp-controller="Artist" asp-action="Index">Back to list</a>
                    </p>
                </div>
            </form>
        </div>
        @if (User.IsInRole("admin"))
        {
            <div class="col text-end">
                <a class="btn btn-primary" asp-controller="Artist" asp-action="Create">Create New Artist</a>
            </div>
        }
    </div>


    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(a => a.Artists[0].Name)
                </th>
                @*<th scope="col">
                        @Html.DisplayNameFor(a => a.Artists[0].Members)
                    </th>*@
                <th scope="col">
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var artist in Model.Artists)
            {
                <tr>
                    <td class="col">
                        <a asp-controller="Artist"
                           asp-action="Details"
                           asp-route-id="@artist.ID">
                            @artist.Name
                        </a>
                    </td>
                    @*<td class="col">
                            @artist.Members
                        </td>*@
                    <td class="col">
                        @if (User.IsInRole("admin"))
                        {<span>
                                <a asp-controller="Artist"
                                   asp-action="Edit"
                                   asp-route-id="@artist.ID">Edit</a> |
                                <a asp-controller="Artist"
                                   asp-action="Delete"
                                   asp-route-id="@artist.ID">Delete</a>
                            </span>
                        }
                    </td>
                    <th class="col">
                        &nbsp;
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>