Music.db/Music.db/Controllers/SongController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music.db.Data;
using Music.db.Models;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    [Authorize(Roles = "admin")]
    public class SongController : Controller
    {
        private readonly MusicDbContext _context;

        public SongController(MusicDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            SongListViewModel viewModel = new SongListViewModel();
            viewModel.Songs = await _context.Songs.Include(a => a.Album)
                                                  .Include(b => b.Remixer)
                                                  .OrderByDescending(x => x.ReleaseDate)
                                                  .ToListAsync();

            viewModel.SongArtists = await _context.SongArtists.Include(x => x.Artist).ToListAsync();

            return View(viewModel);
        }

        //public IActionResult CreateOffCanvas()
        //{
        //    return View();
        //}

        #region Create
        public async Task<IActionResult> Create()
        {
            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            CreateSongViewModel viewModel = new CreateSongViewModel()
            {
                //SelectListItem with default null value 
                Albums = new SelectList(albums.OrderBy(x => x.AlbumTitle), "ID", "AlbumTitle", 0),
                Genres = new SelectList(await _context.Genres.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 0),
                Artists = new SelectList(await _context.Artists.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 1),
                Remixers = new SelectList(remixers.OrderBy(x => x.Name), "ID", "Name", 0)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSongViewModel viewModel)
        {
            Song songindb = await _context.Songs.Where(x => x.SongTitle == viewModel.SongTitle)
                                       .Where(x => x.AlbumID == viewModel.AlbumID)
                                       .Where(x => x.BPM == viewModel.BPM)
                                       .Where(x => x.EditSongLength == viewModel.EditSongLength)
                                       .Where(x => x.ExtendedSongLength == viewModel.ExtendedSongLength)
                                       .Where(x => x.GenreID == viewModel.GenreID)
                                       .Where(x => x.Key == viewModel.Key)
                                       .Where(x => x.ReleaseDate == viewModel.ReleaseDate)
                                       .Where(x => x.RemixerID == viewModel.RemixerID)
                                       .FirstOrDefaultAsync();

            if (songindb != null)
            {
                ModelState.AddModelError("DuplicateError", "Error, you tried to make a duplicate!");
            }

            if (viewModel.EditSongLength == null && viewModel.ExtendedSongLength == null)
            {
                ModelState.AddModelError("SongLenghtError", "Error, a song has at least one length!");
            }

            if (ModelState.IsValid)
            {
                Song song = new Song()
                {
                    SongTitle = viewModel.SongTitle,
                    AlbumID = (viewModel.AlbumID == 0) ? null : viewModel.AlbumID,
                    GenreID = viewModel.GenreID,
                    RemixerID = (viewModel.RemixerID == 0) ? null : viewModel.RemixerID,
                    BPM = viewModel.BPM,
                    EditSongLength = viewModel.EditSongLength,
                    ExtendedSongLength = viewModel.ExtendedSongLength,
                    Key = viewModel.Key,
                    ReleaseDate = viewModel.ReleaseDate,
                };

                _context.Add(song);
                await _context.SaveChangesAsync();

                foreach (var artist in viewModel.SelectedArtists)
                {
                    SongArtist songArtist = new SongArtist()
                    {
                        SongID = song.ID,
                        ArtistID = artist
                    };
                    _context.Add(songArtist);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            viewModel.Albums = new SelectList(albums.OrderBy(x => x.AlbumTitle), "ID", "AlbumTitle", 0);
            viewModel.Genres = new SelectList(await _context.Genres.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 0);
            viewModel.Artists = new SelectList(await _context.Artists.OrderBy(x => x.Name).ToListAsync(), "ID", "Name", 1);
            viewModel.Remixers = new SelectList(remixers.OrderBy(x => x.Name), "ID", "Name", 0);

            return View(viewModel);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FirstOrDefaultAsync(k => k.ID == id);
            if (song == null)
            {
                return NotFound();
            }

            DeleteSongViewModel viewModel = new DeleteSongViewModel()
            {
                SongID = song.ID,
                SongTitle = song.SongTitle,
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ICollection<SongArtist> songArtists = await _context.SongArtists.Where(x => x.SongID == id).ToListAsync();

            foreach (var songArtist in songArtists)
            {
                _context.SongArtists.Remove(songArtist);
            }
            var song = await _context.Songs.FindAsync(id);
            _context.Songs.Remove(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Song song = _context.Songs.Include(x => x.Album)
                                      .Include(x => x.Genre)
                                      .Include(x => x.Remixer)
                                      .Include(x => x.SongArtists)
                                      .Where(x => x.ID == id)
                                      .FirstOrDefault();

            ICollection<SongArtist> songArtists = _context.SongArtists.Include(x => x.Artist)
                                                                      .Where(x => x.SongID == song.ID).ToList();

            if (song != null)
            {
                SongDetailsViewModel viewModel = new SongDetailsViewModel()
                {
                    SongTitle = song.SongTitle,
                    SongArtists = songArtists,
                    Album = song.Album,
                    Genre = song.Genre,
                    Remixer = song.Remixer,
                    BPM = song.BPM,
                    EditSongLength = song.EditSongLength,
                    ExtendedSongLength = song.ExtendedSongLength,
                    Key = song.Key,
                    ReleaseDate = song.ReleaseDate,
                };
                return View(viewModel);
            }
            else
            {
                SongListViewModel viewModel = new SongListViewModel()
                {
                    Songs = _context.Songs.ToList()
                };
                return View("Index", viewModel);
            }
        }

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            ICollection<Album> albums = await _context.Albums.ToListAsync();
            albums.Add(new Album { AlbumTitle = "Single released." });

            ICollection<Artist> remixers = await _context.Artists.ToListAsync();
            remixers.Add(new Artist { Name = "Original version." });

            ICollection<SongArtist> songArtists = await _context.SongArtists.Include(x => x.Artist)
                                                          .Where(x => x.SongID == song.ID).ToListAsync();

            string artistNames = "";
            foreach (var artist in songArtists)
            {
                artistNames += $"{artist.Artist.Name}, ";
            }

            EditSongViewModel viewModel = new EditSongViewModel()
            {
                SongID = song.ID,
                SongTitle = song.SongTitle,
                ArtistNames = artistNames,
                AlbumID = song.AlbumID,
                GenreID = song.GenreID,
                RemixerID = song.RemixerID,

Music.db/Music.db/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Music.db.Areas.Identity.Data;
using Music.db.Data;
using Music.db.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music.db.Controllers
{
    //Login als admin
    //Username = admin  Password = adminn

    //Login als user
    //Username = user   Password = userrr
    //[Authorize(Roles = "admin")]
    public class UserController : Controller
    {
        private UserManager<CustomUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<CustomUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            UserListViewModel viewModel = new UserListViewModel()
            {
                Users = _userManager.Users.ToList()
            };

            return View(viewModel);
        }

        #region Details
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CustomUser user = _userManager.Users.Where(x => x.Id == id).FirstOrDefault();

            if (user != null)
            {
                UserDetailsViewModel viewModel = new UserDetailsViewModel()
                {
                    UserID = user.Id,
                    UserName = user.UserName,
                    Firstname = user.Firstname,
                    Lastname = user.Lastname,
                    Email = user.Email,
                    //Role = user.Role
                };

                return View(viewModel);
            }
            else
            {
                UserListViewModel viewModel = new UserListViewModel()
                {
                    Users = _userManager.Users.ToList()
                };
                return View("Index", viewModel);
            }
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            DeleteUserViewModel viewModel = new DeleteUserViewModel()
            {
                UserID = user.Id,
                UserName = user.UserName,
                Firstname = user.Firstname,
                Lastname = user.Lastname
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            CustomUser user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "User Not Found");
            }

            return View("Index", _userManager.Users.ToList());
        }
        #endregion

        #region GrantPermissions
        public IActionResult GrantPermissions()
        {
            GrantPermissionsViewModel viewModel = new GrantPermissionsViewModel()
            {
                Users = new SelectList(_userManager.Users.ToList(), "Id", "UserName"),
                Roles = new SelectList(_roleManager.Roles.ToList(), "Id", "Name")
            };

            return View(viewModel);
        }

        [HttpPost, ActionName("GrantPermissions")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GrantPermissionsConfirmed(GrantPermissionsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                CustomUser user = await _userManager.FindByIdAsync(viewModel.UserID);
                IdentityRole role = await _roleManager.FindByIdAsync(viewModel.RoleID);

                if (user != null && role != null)
                {
                    IdentityResult result = await _userManager.AddToRoleAsync(user, role.Name);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (IdentityError error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", "User or role not found.");
                }
            }
            return View(viewModel);
        }
        #endregion

        public IActionResult Search(UserListViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.UserSearch))
            {
                viewModel.Users = _userManager.Users.Where(x => x.Firstname.Contains(viewModel.UserSearch) ||
                                                            x.Lastname.Contains(viewModel.UserSearch) ||
                                                            x.UserName.Contains(viewModel.UserSearch)).ToList();
            }
            else
            {
                viewModel.Users = _userManager.Users.ToList();
            }
            return View("Index", viewModel);
        }
    }
}

Music.db/Music.db/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Music.db</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Music.db</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Music.db - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Music.db/Music.db/Views/Shared/_MusicdbLayout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Music.db | @ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="icon" type="image/x-icon" href="~/boombox.ico">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="h-100">
    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="bi bi-boombox"></i> Music.db</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row-reverse" id="navbarTop">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Songs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Create">*Create*</a>
                            </li>*@
                        @*<li>
                            <form asp-controller="Song" asp-action="Search" method="get" class="d-flex">
                                    <input class="form-control me-3" asp-for="SongSearch"/>
                                    <input type="submit" value="Search" class="btn btn-warning" />
                            </form>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container pt-5">
        <main role="main" class="pb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; <span id="year"></span> - Dennis Nijs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            @if (User.IsInRole("admin"))
            {
                <a class="float-end" asp-controller="User" asp-action="Index"><i class="bi bi-people-fill"></i> Manage Users</a>
            }
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>